version: '3.8'
services:
  arcadia-manager-mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${HOST_DB_PORT}:3306"
    volumes:
      - arcadia-manager-db-data:/var/lib/mysql
    restart: unless-stopped
  arcadia-manager-api:
    build: .
    ports:
      - "${PORT}:3000"
    depends_on:
      - arcadia-manager-mysql-db
    environment:
      DATABASE_HOST: mysql-db
      DATABASE_PORT: 3306
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped
    volumes:
      - /root/scripts:/scripts
volumes:
  arcadia-manager-db-data:
    driver: local